### ISSUE TITLE
Fail to start kreator.js

### ISSUE THREAD

**Issue by Kabouik** [piatra/kreator.js#35]
Hi there,

First, thanks a lot for the GUI editor initiative (and a free alternative to slid.es)!

I downloaded all the files, run `npm install` and got no issue at this point, but something goes wrong when I try to actually run kreator.js with `npm run start`. Here is what I get in npm-debug.log:

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart kreator.js@
7 info start kreator.js@
8 verbose unsafe-perm in lifecycle true
9 info kreator.js@ Failed to exec start script
10 error kreator.js@ start: `./node_modules/http-server/bin/http-server`
10 error Exit status 1
11 error Failed at the kreator.js@ start script.
11 error This is most likely a problem with the kreator.js package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     ./node_modules/http-server/bin/http-server
11 error You can get their info via:
11 error     npm owner ls kreator.js
11 error There is likely additional logging output above.
12 error System Windows_NT 6.2.9200
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error cwd C:\Users\user\Desktop\kreator.js-master
15 error node -v v0.10.26
16 error npm -v 1.4.3
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

I am trying to run it on Windows 8.1. Any ideas on how to solve that? Thanks in advance!

[Edit] Alright, I got the server running by using `npm run start` in `kreator.js-master\node_modules\http-server` directory, but still can't use the editor (the interface is unresponsive if I open index.html and try to create/edit my presentations there). I suppose I should only go to localhost:8080 but it only shows the node.js rocket/tortoise picture. I guess running `npm run start` from the above directory does not start every requirements.

[Edit 2] Managed to get `npm run start` working in a Linux VM, but the interface of kreator.js on localhost:8080 is still unresponsive in Firefox. The theme menu kind of works, but the selected theme won't apply. What doesn't work: uploading an index.html, adding slides, setting a title, downloading, hiding the side bar, showing tour, adding anything to the slide (I have not the toolbar I've seen in the kreator.js Youtube video), using device as remote. It seems clicking on buttons and links just does nothing, clicking on the background doesn't either, and the toolbar is missing.

**Comment by piatra** [comment]
Updated the README.
