### ISSUE TITLE
Installing NPM and Node.js needs to use a different repo on Ubuntu 14

### ISSUE THREAD

**Issue by greyeagle** [piatra/kreator.js#38]
If I follow the instructions to install locally, I will get missing file errors and the npm server will not run. 
Updating in the following way helps:

sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs

Hope it helps someone.

Cheers

**Comment by piatra** [comment]
Cheers. I'll add this to the README.
