### ISSUE TITLE
kreator.js problem Windows7

### ISSUE THREAD

**Issue by suckiden** [piatra/kreator.js#39]
I already got the npm installed but when I try to "npm run start" I get the following erros

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart kreator.js@
7 info start kreator.js@
8 verbose unsafe-perm in lifecycle true
9 info kreator.js@ Failed to exec start script
10 error kreator.js@ start: `./node_modules/http-server/bin/http-server`
10 error Exit status 1
11 error Failed at the kreator.js@ start script.
11 error This is most likely a problem with the kreator.js package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     ./node_modules/http-server/bin/http-server
11 error You can get their info via:
11 error     npm owner ls kreator.js
11 error There is likely additional logging output above.
12 error System Windows_NT 6.1.7601
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error cwd C:\Program Files (x86)\kreator.js-master
15 error node -v v0.10.33
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

when I open index.html it looks like this

![chrome](https://cloud.githubusercontent.com/assets/9496980/4871897/df7a7fe4-61cc-11e4-8bc6-c15956475242.png)

EDIT: I also tried it on my Fedora installation (npm commands did work but had no access over localhost:8080) an by just opening the index.html I had the same result. Is there an important step I missed?

**Comment by piatra** [comment]
The reason it doesn't work in Windows is due to the path `./node_modules/http-server/bin/http-server` of the http server that I try to launch. But if you install it yourself with `npm install -g http-server` and then start it with `http-server` (in the kreator.js directory) it should work just fine. 
You can also use python to start an http server `python -m SimpleHTTPServer` in the kreator.js directory.
Sorry about the confusion.

**Comment by piatra** [comment]
Updated the README accordingly.
